install:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
before_build:
  - cd src
  - nuget restore
  - cd ..
version: 1.0.{build}
os: Visual Studio 2015 CTP 6
build:
  verbosity: minimal
test:
  assemblies:
    - '**\*.Tests.dll'
